# CMake generated Testfile for 
# Source directory: E:/firefly/core/tests
# Build directory: E:/firefly/core/build_cpu/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("FireflyTests" "E:/firefly/core/build_cpu/tests/Debug/firefly_tests.exe")
  set_tests_properties("FireflyTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;7;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("FireflyTests" "E:/firefly/core/build_cpu/tests/Release/firefly_tests.exe")
  set_tests_properties("FireflyTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;7;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("FireflyTests" "E:/firefly/core/build_cpu/tests/MinSizeRel/firefly_tests.exe")
  set_tests_properties("FireflyTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;7;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("FireflyTests" "E:/firefly/core/build_cpu/tests/RelWithDebInfo/firefly_tests.exe")
  set_tests_properties("FireflyTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;7;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
else()
  add_test("FireflyTests" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("PresolveTests" "E:/firefly/core/build_cpu/tests/Debug/test_presolve.exe")
  set_tests_properties("PresolveTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;14;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("PresolveTests" "E:/firefly/core/build_cpu/tests/Release/test_presolve.exe")
  set_tests_properties("PresolveTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;14;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("PresolveTests" "E:/firefly/core/build_cpu/tests/MinSizeRel/test_presolve.exe")
  set_tests_properties("PresolveTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;14;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("PresolveTests" "E:/firefly/core/build_cpu/tests/RelWithDebInfo/test_presolve.exe")
  set_tests_properties("PresolveTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;14;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
else()
  add_test("PresolveTests" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("PresolveRulesTests" "E:/firefly/core/build_cpu/tests/Debug/test_presolve_rules.exe")
  set_tests_properties("PresolveRulesTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;18;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("PresolveRulesTests" "E:/firefly/core/build_cpu/tests/Release/test_presolve_rules.exe")
  set_tests_properties("PresolveRulesTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;18;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("PresolveRulesTests" "E:/firefly/core/build_cpu/tests/MinSizeRel/test_presolve_rules.exe")
  set_tests_properties("PresolveRulesTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;18;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("PresolveRulesTests" "E:/firefly/core/build_cpu/tests/RelWithDebInfo/test_presolve_rules.exe")
  set_tests_properties("PresolveRulesTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;18;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
else()
  add_test("PresolveRulesTests" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("SimplexTests" "E:/firefly/core/build_cpu/tests/Debug/test_simplex.exe")
  set_tests_properties("SimplexTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;22;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("SimplexTests" "E:/firefly/core/build_cpu/tests/Release/test_simplex.exe")
  set_tests_properties("SimplexTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;22;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("SimplexTests" "E:/firefly/core/build_cpu/tests/MinSizeRel/test_simplex.exe")
  set_tests_properties("SimplexTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;22;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("SimplexTests" "E:/firefly/core/build_cpu/tests/RelWithDebInfo/test_simplex.exe")
  set_tests_properties("SimplexTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;22;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
else()
  add_test("SimplexTests" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("PDLPTests" "E:/firefly/core/build_cpu/tests/Debug/test_pdlp.exe")
  set_tests_properties("PDLPTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;26;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("PDLPTests" "E:/firefly/core/build_cpu/tests/Release/test_pdlp.exe")
  set_tests_properties("PDLPTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;26;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("PDLPTests" "E:/firefly/core/build_cpu/tests/MinSizeRel/test_pdlp.exe")
  set_tests_properties("PDLPTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;26;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("PDLPTests" "E:/firefly/core/build_cpu/tests/RelWithDebInfo/test_pdlp.exe")
  set_tests_properties("PDLPTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;26;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
else()
  add_test("PDLPTests" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("test_pdlp_concurrency" "E:/firefly/core/build_cpu/tests/Debug/test_pdlp_concurrency.exe")
  set_tests_properties("test_pdlp_concurrency" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;30;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("test_pdlp_concurrency" "E:/firefly/core/build_cpu/tests/Release/test_pdlp_concurrency.exe")
  set_tests_properties("test_pdlp_concurrency" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;30;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("test_pdlp_concurrency" "E:/firefly/core/build_cpu/tests/MinSizeRel/test_pdlp_concurrency.exe")
  set_tests_properties("test_pdlp_concurrency" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;30;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("test_pdlp_concurrency" "E:/firefly/core/build_cpu/tests/RelWithDebInfo/test_pdlp_concurrency.exe")
  set_tests_properties("test_pdlp_concurrency" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;30;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
else()
  add_test("test_pdlp_concurrency" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("test_pdlp_cross_validation" "E:/firefly/core/build_cpu/tests/Debug/test_pdlp_cross_validation.exe")
  set_tests_properties("test_pdlp_cross_validation" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;34;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("test_pdlp_cross_validation" "E:/firefly/core/build_cpu/tests/Release/test_pdlp_cross_validation.exe")
  set_tests_properties("test_pdlp_cross_validation" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;34;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("test_pdlp_cross_validation" "E:/firefly/core/build_cpu/tests/MinSizeRel/test_pdlp_cross_validation.exe")
  set_tests_properties("test_pdlp_cross_validation" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;34;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("test_pdlp_cross_validation" "E:/firefly/core/build_cpu/tests/RelWithDebInfo/test_pdlp_cross_validation.exe")
  set_tests_properties("test_pdlp_cross_validation" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;34;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
else()
  add_test("test_pdlp_cross_validation" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("test_pdlp_stability" "E:/firefly/core/build_cpu/tests/Debug/test_pdlp_stability.exe")
  set_tests_properties("test_pdlp_stability" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;38;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("test_pdlp_stability" "E:/firefly/core/build_cpu/tests/Release/test_pdlp_stability.exe")
  set_tests_properties("test_pdlp_stability" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;38;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("test_pdlp_stability" "E:/firefly/core/build_cpu/tests/MinSizeRel/test_pdlp_stability.exe")
  set_tests_properties("test_pdlp_stability" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;38;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("test_pdlp_stability" "E:/firefly/core/build_cpu/tests/RelWithDebInfo/test_pdlp_stability.exe")
  set_tests_properties("test_pdlp_stability" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;38;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
else()
  add_test("test_pdlp_stability" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("test_gpu_unavailability" "E:/firefly/core/build_cpu/tests/Debug/test_gpu_unavailability.exe")
  set_tests_properties("test_gpu_unavailability" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;42;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("test_gpu_unavailability" "E:/firefly/core/build_cpu/tests/Release/test_gpu_unavailability.exe")
  set_tests_properties("test_gpu_unavailability" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;42;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("test_gpu_unavailability" "E:/firefly/core/build_cpu/tests/MinSizeRel/test_gpu_unavailability.exe")
  set_tests_properties("test_gpu_unavailability" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;42;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("test_gpu_unavailability" "E:/firefly/core/build_cpu/tests/RelWithDebInfo/test_gpu_unavailability.exe")
  set_tests_properties("test_gpu_unavailability" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;42;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
else()
  add_test("test_gpu_unavailability" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("test_pdlp_ruiz" "E:/firefly/core/build_cpu/tests/Debug/test_pdlp_ruiz.exe")
  set_tests_properties("test_pdlp_ruiz" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;46;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("test_pdlp_ruiz" "E:/firefly/core/build_cpu/tests/Release/test_pdlp_ruiz.exe")
  set_tests_properties("test_pdlp_ruiz" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;46;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("test_pdlp_ruiz" "E:/firefly/core/build_cpu/tests/MinSizeRel/test_pdlp_ruiz.exe")
  set_tests_properties("test_pdlp_ruiz" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;46;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("test_pdlp_ruiz" "E:/firefly/core/build_cpu/tests/RelWithDebInfo/test_pdlp_ruiz.exe")
  set_tests_properties("test_pdlp_ruiz" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;46;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
else()
  add_test("test_pdlp_ruiz" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("test_branch_and_bound" "E:/firefly/core/build_cpu/tests/Debug/test_branch_and_bound.exe")
  set_tests_properties("test_branch_and_bound" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;56;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("test_branch_and_bound" "E:/firefly/core/build_cpu/tests/Release/test_branch_and_bound.exe")
  set_tests_properties("test_branch_and_bound" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;56;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("test_branch_and_bound" "E:/firefly/core/build_cpu/tests/MinSizeRel/test_branch_and_bound.exe")
  set_tests_properties("test_branch_and_bound" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;56;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("test_branch_and_bound" "E:/firefly/core/build_cpu/tests/RelWithDebInfo/test_branch_and_bound.exe")
  set_tests_properties("test_branch_and_bound" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;56;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
else()
  add_test("test_branch_and_bound" NOT_AVAILABLE)
endif()
