# CMake generated Testfile for 
# Source directory: E:/firefly/core/tests
# Build directory: E:/firefly/core/build_asan/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("FireflyTests" "E:/firefly/core/build_asan/tests/Debug/firefly_tests.exe")
  set_tests_properties("FireflyTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;7;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("FireflyTests" "E:/firefly/core/build_asan/tests/Release/firefly_tests.exe")
  set_tests_properties("FireflyTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;7;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("FireflyTests" "E:/firefly/core/build_asan/tests/MinSizeRel/firefly_tests.exe")
  set_tests_properties("FireflyTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;7;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("FireflyTests" "E:/firefly/core/build_asan/tests/RelWithDebInfo/firefly_tests.exe")
  set_tests_properties("FireflyTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;7;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
else()
  add_test("FireflyTests" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("PresolveTests" "E:/firefly/core/build_asan/tests/Debug/test_presolve.exe")
  set_tests_properties("PresolveTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;14;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("PresolveTests" "E:/firefly/core/build_asan/tests/Release/test_presolve.exe")
  set_tests_properties("PresolveTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;14;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("PresolveTests" "E:/firefly/core/build_asan/tests/MinSizeRel/test_presolve.exe")
  set_tests_properties("PresolveTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;14;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("PresolveTests" "E:/firefly/core/build_asan/tests/RelWithDebInfo/test_presolve.exe")
  set_tests_properties("PresolveTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;14;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
else()
  add_test("PresolveTests" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("PresolveRulesTests" "E:/firefly/core/build_asan/tests/Debug/test_presolve_rules.exe")
  set_tests_properties("PresolveRulesTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;18;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("PresolveRulesTests" "E:/firefly/core/build_asan/tests/Release/test_presolve_rules.exe")
  set_tests_properties("PresolveRulesTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;18;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("PresolveRulesTests" "E:/firefly/core/build_asan/tests/MinSizeRel/test_presolve_rules.exe")
  set_tests_properties("PresolveRulesTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;18;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("PresolveRulesTests" "E:/firefly/core/build_asan/tests/RelWithDebInfo/test_presolve_rules.exe")
  set_tests_properties("PresolveRulesTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;18;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
else()
  add_test("PresolveRulesTests" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("SimplexTests" "E:/firefly/core/build_asan/tests/Debug/test_simplex.exe")
  set_tests_properties("SimplexTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;22;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("SimplexTests" "E:/firefly/core/build_asan/tests/Release/test_simplex.exe")
  set_tests_properties("SimplexTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;22;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("SimplexTests" "E:/firefly/core/build_asan/tests/MinSizeRel/test_simplex.exe")
  set_tests_properties("SimplexTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;22;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("SimplexTests" "E:/firefly/core/build_asan/tests/RelWithDebInfo/test_simplex.exe")
  set_tests_properties("SimplexTests" PROPERTIES  _BACKTRACE_TRIPLES "E:/firefly/core/tests/CMakeLists.txt;22;add_test;E:/firefly/core/tests/CMakeLists.txt;0;")
else()
  add_test("SimplexTests" NOT_AVAILABLE)
endif()
